
import com.toedter.calendar.JDateChooser;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ale
 */
public class Agenda extends javax.swing.JFrame {
    ArrayList Agenda = new ArrayList ();

    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
        CrearModelo();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sss = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Act = new javax.swing.JTextField();
        notad = new javax.swing.JTextField();
        Lug = new javax.swing.JTextField();
        Hor = new javax.swing.JTextField();
        Dur = new javax.swing.JTextField();
        Acomp = new javax.swing.JTextField();
        Tel = new javax.swing.JTextField();
        Direc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        mostrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        DiaDeLaS = new javax.swing.JLabel();
        guard = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        DateChos = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Actividad: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Lugar:");

        sss.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sss.setText("Hora:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Duración:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Acompañantes:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Telefono:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Dirección:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Notas adicionales:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Eventos agendados");

        mostrar.setText("Mostrar");
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel10)
                                .addComponent(jLabel8)
                                .addComponent(jLabel6)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sss)
                                    .addComponent(jLabel4))
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Tel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addComponent(Acomp, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Dur, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Hor, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lug, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Direc)
                    .addComponent(notad)
                    .addComponent(Act, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Act, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(notad, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(38, 38, 38)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lug, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sss))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dur, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Acomp, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Direc, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Agenda 2020");

        DiaDeLaS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DiaDeLaS.setText("Fecha: ");

        guard.setText("Guardar");
        guard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardActionPerformed(evt);
            }
        });

        borrar.setText("Borrar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DiaDeLaS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DateChos, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(guard, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DiaDeLaS)
                    .addComponent(guard, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateChos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardActionPerformed
        // TODO add your handling code here:
        /*String texto1 = (Act.getText());
        String texto2 = (notad.getText());
        String texto3 = (Dur.getText());
        String texto4 = (dd.getText());
        String texto5 = (Hor.getText());
        String texto6 = (Lug.getText());
        String texto7 = (Tel.getText());
        String texto8 = (annio.getText());
        String texto9 = (Direc.getText());
        String texto10 = (mes.getText());
        String texto11=(Acomp.getText());

        if(texto1.isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo actividad vacío");
        }else{
            if(texto3.isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo duración vacío");
            }else{
                if(texto4.isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo día vacío");
            }else{
                if(texto5.isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo hora vacío");
            }else{
                if(texto6.isEmpty()){
            JOptionPane.showMessageDialog(null,"Campo lugar vacío");
            }else{
                if(texto7.isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo telefono vacío");
            }else{
                if(texto8.isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo año vacío");
            }else{
                if(texto9.isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo dirección vacío");
            }else{
                    if(texto10.isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo mes vacío");
            }else{
                    if(texto11.isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo acompañantes vacío");
            }else{
                        
                Agendars ag = new Agendars(texto1,texto2,texto3,texto4,texto5,texto6,texto7,texto8,texto9,texto10,texto11);
                Agenda.add(ag);
                
                JOptionPane.showMessageDialog(null, "Actividad agendada");
            }
        }
        }
        }
        }            
        }
        }
        }
        }
        }*/
        String texto1 = (Act.getText());
        String texto2 = (notad.getText());
        String texto3 = (Dur.getText());
        //String texto4 = (dd.getText());
        String texto5 = (Hor.getText());
        String texto6 = (Lug.getText());
        String texto7 = (Tel.getText());
        String texto9 = (Direc.getText());
        String texto11=(Acomp.getText());
        
     
        if(texto1.isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo actividad vacío");
        }else{
            if(texto3.isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo duración vacío");
            }else{
                /*if(texto4.isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo día vacío");
            }else{*/
                if(texto5.isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo hora vacío");
            }else{
                if(texto6.isEmpty()){
            JOptionPane.showMessageDialog(null,"Campo lugar vacío");
            }else{
                if(texto7.isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo telefono vacío");
            }else{
                if(texto9.isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo dirección vacío");
            }else{
                    if(texto11.isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo acompañantes vacío");
            }else{
                        
                Agendars ag = new Agendars(texto1,texto2,texto3,/*texto4,*/texto5,texto6,texto7,texto9,texto11);
                Agenda.add(ag);
                
                JOptionPane.showMessageDialog(null, "Actividad agendada");
            }
        }
        }            
        }
        }
        }
        }
        
    }//GEN-LAST:event_guardActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        // TODO add your handling code here:
        Act.setText(String.valueOf(""));
        notad.setText(String.valueOf(""));
        Lug.setText(String.valueOf(""));
        Hor.setText(String.valueOf(""));
        Dur.setText(String.valueOf(""));
        Acomp.setText(String.valueOf(""));
        Tel.setText(String.valueOf(""));
        Direc.setText(String.valueOf(""));
        DateChos.setCalendar(null);
        
      
        //JDateChooser setDate = DateChos.setDate(new Date);
        //dd.setText(String.valueOf(""));
        //mes.setText(String.valueOf(""));
        //annio.setText(String.valueOf(""));
    }//GEN-LAST:event_borrarActionPerformed

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        // TODO add your handling code here:
        Object ar[] = null;
        
        for(int i=0; i<Agenda.size();i++ ){
          Agendars a = (Agendars) Agenda.get(i);
          
          Mod.addRow(ar);
          Mod.setValueAt(a.getAct1(), i, 0);
          Mod.setValueAt(a.getLug1(), i, 1);
          Mod.setValueAt(a.getHor1(), i, 2);
          Mod.setValueAt(a.getDur1(), i, 3);
          Mod.setValueAt(a.getAcomp1(), i, 4);
          Mod.setValueAt(a.getTel1(), i, 5);
          Mod.setValueAt(a.getDirec1(), i, 6);
          
          SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
          /*Date da = DateChos.getDate();
          
          long di= da.getTime();
          java.sql.Date fec = new java.sql.Date(di);*/
          
          String date = dFormat.format(DateChos.getDate());

          Mod.setValueAt(date,i, 7);
       
          //Mod.setValueAt(a.getMes1(), i, 7);
          //Mod.setValueAt(a.getAnnio1(), i, 7);
          Mod.setValueAt(a.getNotad1(), i, 8);
        }   
    }//GEN-LAST:event_mostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    DefaultTableModel Mod;
    
    private void CrearModelo(){
        try{
            Mod = (new DefaultTableModel(null, new String[]{
             "Actividad","Lugar","Hora","Duracion","Acompañantes", "Teléfono", "Direccion", "Fecha", "Notas adicionales"}){});
            jTable1.setModel(Mod);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error");
        }
            
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Acomp;
    private javax.swing.JTextField Act;
    private com.toedter.calendar.JDateChooser DateChos;
    private javax.swing.JLabel DiaDeLaS;
    private javax.swing.JTextField Direc;
    private javax.swing.JTextField Dur;
    private javax.swing.JTextField Hor;
    private javax.swing.JTextField Lug;
    private javax.swing.JTextField Tel;
    private javax.swing.JButton borrar;
    private javax.swing.JButton guard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton mostrar;
    private javax.swing.JTextField notad;
    private javax.swing.JLabel sss;
    // End of variables declaration//GEN-END:variables
}
